# -*- coding: utf-8 -*-
"""python_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZiWjvhbkIAb574D61iSs4-GnpCbq4olS
"""

import requests

#git url

url = "https://raw.githubusercontent.com/WahuElizabethKE/phone-store-data/refs/heads/main/MOCK_DATA%20(1).json"

#send request
phone_store_data = requests.get(url)

phone_data = phone_store_data.json()

#checking data type
# Python Lists vs. Dictionaries:
# Lists:
# - Ordered collection of items.
# - Items are accessed by their integer index (e.g., my_list[0]).
# - Can contain duplicate items.
# - Enclosed in square brackets [].
# Example: [1, 2, 3, 'apple', 'banana']

# Dictionaries:
# - Unordered collection of key-value pairs.
# - Items are accessed by their unique keys (e.g., my_dict['name']).
# - Keys must be unique and immutable (e.g., strings, numbers, tuples).
# - Values can be of any type and can be duplicated.
# - Enclosed in curly braces {} with key:value pairs.
# Example: {'name': 'Alice', 'age': 30, 'city': 'New York'}

# In your current notebook, 'phone_data' is a list of dictionaries.
# Each dictionary within the list represents a phone with keys like 'brand', 'year', 'price', etc.

type(phone_data)

phone_data

#viewing the last five dict

phone_data[-5:]

#selecting one dict
phone_data_dict = phone_data[1]

"""phone_data = lists

phone_data_dict = dictionary

"""

phone_data_dict

print(phone_data_dict)

type(phone_data_dict)

#veiwing keys

phone_data_dict.keys()

#veiwing values

phone_data_dict.values()

#viewing some of the values

print("Brand:", phone_data_dict['brand'])
print("Year:", phone_data_dict['year'])
print("Price:", phone_data_dict['price'])

#gets key for price
phone_data_dict.get("price")

# Counting the number of dictionaries (items) in the list 'phone_data'
num_items = len(phone_data)
print(len(phone_data))

#adding new key = in_stock

for phone_data_dict in phone_data:
    phone_data_dict["in_stock"] = "yes"

#checking if it has been added

phone_data[50]

# Get elements from index 10 to 14 (inclusive of 10, exclusive of 15)

in_stock = phone_data[10:15]
in_stock

for item in phone_data:
    print(item)

# Initialize a variable to store the total price
total_price = 0

# Iterate through each dictionary in the phone_data list
for phone in phone_data:
    # Add the 'price' value of each phone to the total_price
    total_price += phone['price']

# Print the total sum of prices
print(f"The total sum of all phone prices is: {total_price}")

#sum of phone price

total_price = 0

for phone in phone_data:
  total_price += phone['price']

total_price

#sliced data

in_stock = phone_data[10:15]
in_stock

import pandas

#creating a data frame
phone_df = pandas.DataFrame(in_stock)

phone_df

#saving to cvs
phone_df.to_csv("phone_data.cvs")

print("phone_data.cvs saved successfully")



"""**Part 3**"""

#dummy
import requests

beauty_url = "https://dummyjson.com/products"

beauty_shop = requests.get(beauty_url)

beauty_data = beauty_shop.json()

print(type(beauty_data))

beauty_data.keys()

len(beauty_data)

beauty_data

import pandas as pd

#creating a data frame
beauty_df = pd.DataFrame(beauty_data['products'])

beauty_df

#saving to cvs

beauty_df.to_csv("dummyjson_products.csv", index=False)
print("✅ Products saved to dummyjson_products.csv\n")

"""#Carts"""

#carts
import requests
cart_url = "https://dummyjson.com/carts"

print("Fetching Carts...")

carts_response = requests.get(cart_url)

carts_data = carts_response.json()

carts_data

carts_data.keys()

import pandas

carts_df = pandas.DataFrame(carts_data)

carts_df

carts_df.to_csv("dummyjson_carts.csv", index=False)
print("✅ Carts saved to dummyjson_carts.csv")